#define SECRET_SSID "<Your WiFi SSID here>"
#define SECRET_PASS "<You WiFi PASSWORD here>"
#define SECRET_NTP_TIMEZONE "Europe/Lisbon"
#define SECRET_NTP_TIMEZONE_CODE "WET0WEST,M3.5.0/1,M10.5.0"
#define SECRET_NTP_SERVER_1 "2.pt.pool.ntp.org"
#define SECRET_MY_RFID_TAG_NR_HEX "<Your RFID TAG HEX ID lower case> // e.g. "2b8e3942"
